import type { EvaluateResponse } from "@/types";
import DecisionBadge from "./DecisionBadge";
import OfferCard from "./OfferCard";
import ReasonList from "./ReasonList";
import LoadingSkeleton from "./LoadingSkeleton";
import ErrorState from "./ErrorState";
import EmptyState from "./EmptyState";

type WidgetState = {
  status: "idle" | "loading" | "success" | "error";
  result: EvaluateResponse | null;
  error: string | null;
};

type Props = {
  state: WidgetState;
  applicationName?: string;
  applicationId?: number;
  onRetry: () => void;
  onMock: () => void;
};

export default function WidgetCard({ state, applicationName, applicationId, onRetry, onMock }: Props) {
  return (
    <div
      className="mx-auto w-full max-w-[420px] overflow-hidden rounded-2xl shadow-lg"
      style={{ background: "#fff" }}
    >
      {/* Header */}
      <div className="border-b px-5 py-4" style={{ borderColor: "#f1f5f9" }}>
        <div className="flex items-start justify-between gap-2">
          <div>
            <p className="text-sm font-semibold text-slate-900">
              {applicationName ?? "—"}
            </p>
            {applicationId && (
              <p className="text-xs text-slate-400">
                App #{applicationId}
              </p>
            )}
          </div>
          {state.result?.bestOffer && (
            <DecisionBadge status={state.result.bestOffer.status} />
          )}
        </div>
      </div>

      {/* Body */}
      <div className="min-h-[300px]">
        {state.status === "idle" && <EmptyState />}
        {state.status === "loading" && <LoadingSkeleton />}
        {state.status === "error" && <ErrorState error={state.error!} onRetry={onRetry} onMock={onMock} />}
        {state.status === "success" && state.result && <WidgetContent result={state.result} />}
      </div>

      {/* Footer */}
      <div className="border-t px-5 py-3 text-center" style={{ borderColor: "#f1f5f9" }}>
        <p className="text-[10px] font-medium uppercase tracking-wider text-slate-300">
          Generated by Lens IQ
        </p>
      </div>
    </div>
  );
}

function WidgetContent({ result }: { result: EvaluateResponse }) {
  const best = result.bestOffer;
  const otherOffers = best ? result.offers.filter((o) => o.programId !== best.programId || o.bankId !== best.bankId) : result.offers;

  return (
    <div className="space-y-4 p-5">
      {/* Best Offer */}
      {best && <OfferCard offer={best} isBest />}

      {/* Reasons */}
      {best && best.reasons.length > 0 && (
        <div>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Key Factors
          </p>
          <ReasonList reasons={best.reasons} />
        </div>
      )}

      {/* Other Offers */}
      {otherOffers.length > 0 && (
        <div>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">
            Other Offers ({otherOffers.length})
          </p>
          <div className="flex snap-x snap-mandatory gap-3 overflow-x-auto pb-2">
            {otherOffers.map((offer) => (
              <div key={offer.programId} className="min-w-[280px] snap-start">
                <OfferCard offer={offer} />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* No offers */}
      {!best && result.offers.length === 0 && (
        <div className="flex flex-col items-center justify-center py-8 text-center">
          <p className="text-sm font-semibold text-slate-500">No offers available</p>
        </div>
      )}
    </div>
  );
}
