import type { Program } from "../../shared/types/program.js";

export function createTestProgram(overrides?: Partial<Program>): Program {
    return {
        id: 1,
        tenantId: 1,
        name: "Test Program",
        code: null,
        description: null,
        customerTypes: ["salary_transfer"],
        priority: 0,
        requiredDocuments: [],
        defaultRiskRules: null,
        financingType: "conventional",
        calculationMethod: "reducing",
        interestRate: 14.5,
        minDownPaymentPercent: 10,
        maxDownPaymentPercent: 100,
        maxMonths: 60,
        minMonths: 12,
        minSalary: 5000,
        maxCustomerAge: 60,
        maxCarAge: 10,
        allowedConditions: "both",
        maxVehiclePrice: null,
        profitRate: null,
        maxFinanceAmount: null,
        adminFeesPercent: 1,
        salaryTransferRequired: false,
        active: true,
        banks: [{
            programId: 1,
            bankId: 1,
            bankName: "Test Bank",
            active: true,
            interestRate: 13.5,
            profitRate: null,
            minMonths: 12,
            maxMonths: 60,
            minDownPaymentPercent: 15,
            maxDownPaymentPercent: 100,
            maxFinanceAmount: null,
            adminFeesPercent: 1,
            maxCarAge: 10,
            maxVehiclePrice: null,
        }],
        ...overrides,
    };
}